spring.application.name=apptest-api

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health, info, loggers
management.endpoint.health.show-details=always
management.endpoint.loggers.enabled=true